sudo: required
before_install:
  - sudo apt-get install ninja-build
language: cpp
compiler:
  - gcc
script:
  - mkdir build
  - cd build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_WARNINGS=OFF ..
  - ninja
  - ninja check-all

